# variables:
#   AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
#   AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
#   AWS_REGION: $AWS_REGION
#   AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION

# stages:
#   # - test
#   - deploy


# # test: 
# #   image: node:12.4.0
# #   stage: test
# #   script:
# #     - npm install 
# #     - npm run lint

# deploy: 
#   image: amaysim/serverless:2.11.0
#   stage: deploy
#   before_script:
#     - FAILURE_MESSAGE="Must define \$AWS_ACCESS_KEY_ID and \$AWS_SECRET_ACCESS_KEY. Add keys to $CI_PROJECT_URL/-/settings/ci_cd"
#     - test -z "$AWS_SECRET_ACCESS_KEY" && echo $FAILURE_MESSAGE && exit 1
#     - test -z "$AWS_ACCESS_KEY_ID" && echo $FAILURE_MESSAGE && exit 1
#   script:
#     - npm install -g serverless
#     - npm install 
#     - serverless deploy --stage production --verbose
#   only:
#       - dev # just for my testing
#       - master

image: node:latest

stages:
  - deploy

production:
  stage: deploy
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
  script:
    - serverless deploy --stage production --verbose
  environment: production
