fnSQS:
  handler: services/infrastructure/sqs/src/index.receiver
  name: sqs-receiver
  description: sqs receiver
  memorySize: 128
  timeout: 25
  role: ${self:custom.imports.SQSLambdaRoleArn}
  events:
    - sqs:
        arn: ${self:custom.imports.QueueARN}
  package:
    individually: true